---

- name: Download and install kapacitor apt public signing key
  apt_key:
    url:   "{{ kapacitor_signing_key_url }}"
    state: present

- name: Add kapacitor apt repository definition to apt sources list
  apt_repository: 
    repo:         "{{ kapacitor_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install kapacitor
  apt: name=kapacitor state=present

- name: Update kapacitor config file
  template:
    src:   kapacitor.conf.j2
    dest:  "{{ kapacitor_conf_dir }}/kapacitor.conf"
    owner: root
    group: root
    mode:  0664
  notify: Restart kapacitor

- name: Update kapacitor startup script envrionment variables file
  template:
    src:   etc.default.kapacitor.j2
    dest:  /etc/default/kapacitor
    owner: root
    group: root
    mode:  0644
  notify: Restart kapacitor

- name: Start kapacitor
  service: name=kapacitor enabled=yes state=started
